name: "Build and evaluate model"

on:
  push:
    branches:
      - "master"

jobs:
  build:
    name: "Build model"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Clone external repo
        run: |
          git clone https://git.wmi.amu.edu.pl/s475257/inzynieria-uczenia-maszynowego external
          cd external

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Download data
        run: |
          python download_and_process.py

      - name: Train model
        run: |
          python train_model.py   

      - name: Upload model as artifact
        uses: actions/upload-artifact@v4
        with:
          name: model
          path: .model/model.pth

  evaluate:
    name: "Evaluate model"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Clone external repo
        run: |
          git clone https://git.wmi.amu.edu.pl/s475257/inzynieria-uczenia-maszynowego external
          cd external

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Download data
        run: |
          python download_and_process.py

      - name: Download model artifact
        uses: actions/download-artifact@v4
        with:
          name: model
          path: .model/model.pth

      - name: Evaluate model
        run: |
          python evaluate_model.py
      
          
      
